/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Llm } from "./llm";
import { Manage } from "./manage";
import { Profile } from "./profile";

export class Dataservice extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    private _profile?: Profile;
    get profile() {
        return (this._profile ??= new Profile(this.options$));
    }

    private _llm?: Llm;
    get llm() {
        return (this._llm ??= new Llm(this.options$));
    }

    private _manage?: Manage;
    get manage() {
        return (this._manage ??= new Manage(this.options$));
    }
}
