/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type PublishResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successful Response
     */
    any?: any | undefined;
};

/** @internal */
export namespace PublishResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        any?: any | undefined;
    };

    export const inboundSchema: z.ZodType<PublishResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            any: z.any().optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.any === undefined ? null : { any: v.any }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        any?: any | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PublishResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            any: z.any().optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.any === undefined ? null : { any: v.any }),
            };
        });
}
